#!/bin/bash

cd /var/www/mediawiki

# Move generic config out of place or installer wont run
mv ./LocalSettings.php /tmp/LocalSettings.php

# Run installer
php maintenance/install.php MyWiki $1 --pass=$2 \
 --dbport=3306 \
 --dbserver=${MEDIAWIKI_DB_HOST} \
 --dbtype=mysql \
 --dbname=${MEDIAWIKI_DB_NAME} \
 --installdbuser=${MEDIAWIKI_DB_USER} \
 --installdbpass=${MEDIAWIKI_DB_PASSWORD} \
 --dbuser=${MEDIAWIKI_DB_USER} \
 --dbpass=${MEDIAWIKI_DB_PASSWORD} \
 --scriptpath=/

# Fix SQLite data folder permissions
chown -R www-data:www-data /data

# Display random generated secret key
echo ""
cat LocalSettings.php | grep -E  'wgSecretKey|wgUpgradeKey'

# Remove config generated by the installer
rm -rf ./LocalSettings.php

# Restore generic config
mv /tmp/LocalSettings.php ./LocalSettings.php
