# Do not forget to create a new database on your first run:
# $ docker exec -it wiki /script/install.sh <username> <password>
version: '2'
services:
  wiki:
    #build: ./../../../ # Uncomment to build from source
    image: kristophjunge/mediawiki
    container_name: wiki
    environment:
      MEDIAWIKI_SERVER: http://localhost
      MEDIAWIKI_SITENAME: MyWiki
      MEDIAWIKI_LANGUAGE_CODE: en
      MEDIAWIKI_SECRET_KEY: a6578339c8f73c8721b43241056d28af5be10dd922cd426ef10f086dd590aa8e
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_PORT: 3306
      MEDIAWIKI_DB_NAME: wikidb
      MEDIAWIKI_DB_USER: wikiuser
      MEDIAWIKI_DB_TABLE_OPTIONS: ENGINE=InnoDB, DEFAULT CHARSET=binary
      MEDIAWIKI_DB_PASSWORD: mysecret
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_ENABLE_VISUAL_EDITOR: 1
      MEDIAWIKI_DEFAULT_SKIN: vector
    ports:
    - "8080:8080"
    links:
    - db:db
    volumes:
    - /srv/mediawiki/images:/images
    #- ./../../../testdata/logo.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    #- ./../../../testdata/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: wikidb
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: mysecret
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
    - /srv/mediawiki2/mysql:/var/lib/mysql
